// ─── 本のデータ ──────────────────────────────────────────────────────
// 本を追加・編集するときはこのファイルだけ変更してください。
//
// 各フィールド:
//   id       : 重複しない数字（新しい本を追加するときは末尾の番号+1）
//   title    : タイトル
//   author   : 著者名
//   year     : 出版年
//   genre    : ジャンル（カードに小さく表示）
//   emoji    : 表紙画像が取得できないときの代替絵文字
//   passage  : 紹介する一節（\n で改行）
//   desc     : あらすじ・紹介文
//   link     : 青空文庫など無料で読めるリンク（なければ shopLink と同じでOK）
//   shopLink : Amazon などの購入・検索リンク

const books = [
  // ── 既存8冊 ────────────────────────────────────────────────────────
  {
    id: 1,
    title: 'こころ',
    author: '夏目漱石',
    year: '1914年',
    genre: '近代文学',
    emoji: '🌕',
    passage: `私はその人を常に先生と呼んでいた。だからここでもただ先生と書くだけで本名は打ち明けない。これは世間を憚かる遠慮というよりも、その方が私にとって自然だからである。`,
    desc: '明治の文豪・夏目漱石が晩年に著した長編小説。「先生」と「私」の交流を通し、個人の孤独と罪、そして明治という時代の終焉を描いた不朽の名作。',
    link: 'https://www.aozora.gr.jp/cards/000148/files/773_14560.html',
    shopLink: 'https://www.amazon.co.jp/s?k=%E3%81%93%E3%81%93%E3%82%8D+%E5%A4%8F%E7%9B%AE%E6%BC%B1%E7%9F%B3',
  },
  {
    id: 2,
    title: '羅生門',
    author: '芥川龍之介',
    year: '1915年',
    genre: '短編小説',
    emoji: '🦅',
    passage: `広い門の下には、この男のほかに誰もいない。ただ、所々丹塗の剥げた、大きな円柱に、蟋蟀が一匹とまっている。`,
    desc: '芥川龍之介の代表作。荒廃した平安京の羅生門を舞台に、生きるために悪を犯すことを正当化していく男の心理を鋭く描いた短編。人間の利己心と道徳の葛藤が今も鮮烈に響く。',
    link: 'https://www.aozora.gr.jp/cards/000879/files/127_15260.html',
    shopLink: 'https://www.amazon.co.jp/s?k=%E7%BE%85%E7%94%9F%E9%96%80+%E8%8A%A5%E5%B7%9D%E9%BE%8D%E4%B9%8B%E4%BB%8B',
  },
  {
    id: 3,
    title: '人間失格',
    author: '太宰治',
    year: '1948年',
    genre: '自伝的小説',
    emoji: '🖋',
    passage: `恥の多い生涯を送って来ました。`,
    desc: '太宰治の遺作。「葉蔵」という主人公が綴った手記という形式で、自己の存在への根源的な疑問と社会への違和感を赤裸々に描く。読む者の心の奥底に確かに触れてくる、日本文学の問題作。',
    link: 'https://www.aozora.gr.jp/cards/000035/files/301_14912.html',
    shopLink: 'https://www.amazon.co.jp/s?k=%E4%BA%BA%E9%96%93%E5%A4%B1%E6%A0%BC+%E5%A4%AA%E5%AE%B0%E6%B2%BB',
  },
  {
    id: 4,
    title: '銀河鉄道の夜',
    author: '宮沢賢治',
    year: '1934年（没後刊）',
    genre: 'ファンタジー文学',
    emoji: '🌌',
    passage: `ではみなさんは、そういうふうに川だと云われたり、乳の流れたあとだと云われたりしていたこのぼんやりと白いものがほんとうは何かご承知ですか`,
    desc: '宮沢賢治が生涯をかけて書き続けた未完の傑作。少年ジョバンニが友カムパネルラとともに銀河鉄道に乗り旅をする物語。命とは何か、本当の幸福とは何かを問い続ける詩的な世界観が広がる。',
    link: 'https://www.aozora.gr.jp/cards/000081/files/43737_19215.html',
    shopLink: 'https://www.amazon.co.jp/s?k=%E9%8A%80%E6%B2%B3%E9%89%84%E9%81%93%E3%81%AE%E5%A4%9C+%E5%AE%AE%E6%B2%A2%E8%B3%A2%E6%B2%BB',
  },
  {
    id: 5,
    title: '雪国',
    author: '川端康成',
    year: '1937年',
    genre: '純文学',
    emoji: '❄️',
    passage: `国境の長いトンネルを抜けると雪国であった。`,
    desc: 'ノーベル文学賞作家・川端康成の代表作。芸者の駒子と東京から訪れる島村の交情を、雪深い温泉地を舞台に叙情豊かに描く。冒頭の一文は日本文学史上もっとも有名な書き出しの一つ。',
    link: 'https://www.aozora.gr.jp/',
    shopLink: 'https://www.amazon.co.jp/s?k=%E9%9B%AA%E5%9B%BD+%E5%B7%9D%E7%AB%AF%E5%BA%B7%E6%88%90',
  },
  {
    id: 6,
    title: '吾輩は猫である',
    author: '夏目漱石',
    year: '1905年',
    genre: '長編小説・諷刺',
    emoji: '🐱',
    passage: `何でも薄暗いじめじめした所でニャーニャー泣いていた事だけは記憶している。`,
    desc: '漱石の処女長編。名もなき猫の目を通して、明治の知識人社会を軽妙に諷刺した作品。語り口のユーモアと鋭い社会批評が絶妙に溶け合い、今も読み継がれる不朽の名作。',
    link: 'https://www.aozora.gr.jp/cards/000148/files/789_14547.html',
    shopLink: 'https://www.amazon.co.jp/s?k=%E5%90%BE%E8%BC%A9%E3%81%AF%E7%8C%AB%E3%81%A7%E3%81%82%E3%82%8B',
  },
  {
    id: 7,
    title: 'やがて哀しき外国語',
    author: '村上春樹',
    year: '1994年',
    genre: 'エッセイ',
    emoji: '✈️',
    passage: `物語を語ることは、ある意味では嘘をつくことだ。`,
    desc: '村上春樹がアメリカ・プリンストン大学に滞在した2年間を綴ったエッセイ集。異国での生活、言語、文化の差異をユーモラスかつ真摯に見つめた、村上文学の入口として最適の一冊。',
    link: 'https://www.amazon.co.jp/s?k=%E3%82%84%E3%81%8C%E3%81%A6%E5%93%80%E3%81%97%E3%81%8D%E5%A4%96%E5%9B%BD%E8%AA%9E',
    shopLink: 'https://www.amazon.co.jp/s?k=%E3%82%84%E3%81%8C%E3%81%A6%E5%93%80%E3%81%97%E3%81%8D%E5%A4%96%E5%9B%BD%E8%AA%9E+%E6%9D%91%E4%B8%8A%E6%98%A5%E6%A8%B9',
  },
  {
    id: 8,
    title: '方丈記',
    author: '鴨長明',
    year: '1212年',
    genre: '随筆・古典',
    emoji: '🌊',
    passage: `ゆく河の流れは絶えずして、しかも、もとの水にあらず。よどみに浮かぶうたかたは、かつ消えかつ結びて、久しくとどまりたるためしなし。`,
    desc: '鎌倉時代の随筆文学。「無常」をテーマに、地震・洪水・飢饉など数々の天変地異と、方丈（一丈四方の庵）での隠遁生活を静かに綴る。800年以上を経ても色あせない普遍的な哲学がある。',
    link: 'https://www.aozora.gr.jp/cards/000196/files/975_20743.html',
    shopLink: 'https://www.amazon.co.jp/s?k=%E6%96%B9%E4%B8%88%E8%A8%98+%E9%B4%A8%E9%95%B7%E6%98%8E',
  },

  // ── 青空文庫・新規追加 ────────────────────────────────────────────
  {
    id: 9,
    title: '坊っちゃん',
    author: '夏目漱石',
    year: '1906年',
    genre: '近代小説',
    emoji: '🏫',
    passage: `親譲りの無鉄砲で子供の時から損ばかりしている。`,
    desc: '漱石が愛媛・松山の中学校に教師として赴任した体験をもとに書いた痛快小説。曲がったことが大嫌いな「坊っちゃん」が教育現場の腐敗と戦う姿は、今なお読者の胸を熱くさせる。',
    link: 'https://www.aozora.gr.jp/cards/000148/files/752_14964.html',
    shopLink: 'https://www.amazon.co.jp/s?k=%E5%9D%8A%E3%81%A3%E3%81%A1%E3%82%83%E3%82%93+%E5%A4%8F%E7%9B%AE%E6%BC%B1%E7%9F%B3',
  },
  {
    id: 10,
    title: '走れメロス',
    author: '太宰治',
    year: '1940年',
    genre: '短編小説',
    emoji: '🏃',
    passage: `メロスは激怒した。必ず、かの邪智暴虐の王を除かなければならぬと決意した。`,
    desc: '太宰治が古代ギリシャの伝説をもとに書いた友情と信頼の物語。「信じられる友がいる」という純粋な確信を描ききった文章は、圧倒的なリズムとともに読む者の魂を揺さぶる。',
    link: 'https://www.aozora.gr.jp/cards/000035/files/1567_14913.html',
    shopLink: 'https://www.amazon.co.jp/s?k=%E8%B5%B0%E3%82%8C%E3%83%A1%E3%83%AD%E3%82%B9+%E5%A4%AA%E5%AE%B0%E6%B2%BB',
  },
  {
    id: 11,
    title: '山月記',
    author: '中島敦',
    year: '1942年',
    genre: '短編小説',
    emoji: '🐯',
    passage: `臆病な自尊心と、尊大な羞恥心と、こいつが己を、かくの如く不幸にしたのだ。`,
    desc: '中国の古典「人虎伝」を下敷きにした傑作短編。詩人を夢見ながら虎に変わった男が、かつての親友に自らの業を語る。プライドと臆病さの間で引き裂かれる人間の本質を描いた名作。',
    link: 'https://www.aozora.gr.jp/cards/000119/files/624_14544.html',
    shopLink: 'https://www.amazon.co.jp/s?k=%E5%B1%B1%E6%9C%88%E8%A8%98+%E4%B8%AD%E5%B3%B6%E6%95%A6',
  },
  {
    id: 12,
    title: '檸檬',
    author: '梶井基次郎',
    year: '1925年',
    genre: '短編小説',
    emoji: '🍋',
    passage: `焦躁と言おうか、嫌悪と言おうか——酒を飲んだあとに宿酔があるように、酒を毎日飲んでいると宿酔に相当した時期がやって来る。`,
    desc: '梶井基次郎の代表作にして処女作。重い倦怠を抱えた語り手が、ある日手にした一個の檸檬に不思議な解放感を覚える。病と貧困の中で書かれた鮮烈な感覚の記録。',
    link: 'https://www.aozora.gr.jp/cards/000074/files/424_19826.html',
    shopLink: 'https://www.amazon.co.jp/s?k=%E6%AA%B8%E6%AA%AC+%E6%A2%B6%E4%BA%95%E5%9F%BA%E6%AC%A1%E9%83%8E',
  },
  {
    id: 13,
    title: '草枕',
    author: '夏目漱石',
    year: '1906年',
    genre: '純文学・詩的小説',
    emoji: '🎨',
    passage: `智に働けば角が立つ。情に棹させば流される。意地を通せば窮屈だ。とかくに人の世は住みにくい。`,
    desc: '漱石が「非人情」の美学を語った詩的小説。画工が山奥の温泉地へと旅をしながら、自然と人間、芸術と人生について思索する。東洋と西洋の美意識が交差する独特の世界観を持つ。',
    link: 'https://www.aozora.gr.jp/cards/000148/files/776_14941.html',
    shopLink: 'https://www.amazon.co.jp/s?k=%E8%8D%89%E6%9E%95+%E5%A4%8F%E7%9B%AE%E6%BC%B1%E7%9F%B3',
  },
  {
    id: 14,
    title: '蜘蛛の糸',
    author: '芥川龍之介',
    year: '1918年',
    genre: '童話・短編',
    emoji: '🕷️',
    passage: `池の中に咲いている蓮の花は、みんな玉のように真白で、そのまん中にある金色の蕊からは、何とも云えない好い匂が、絶間なくあたりへ溢れて居ります。`,
    desc: '芥川が子どもたちのために書いた短編童話。地獄に落ちた大泥棒カンダタに、釈迦が一本の蜘蛛の糸を垂らす——その先にある人間の業と救済を、澄んだ文章で鮮やかに描く。',
    link: 'https://www.aozora.gr.jp/cards/000879/files/92_14545.html',
    shopLink: 'https://www.amazon.co.jp/s?k=%E8%9C%98%E8%9B%9B%E3%81%AE%E7%B3%B8+%E8%8A%A5%E5%B7%9D%E9%BE%8D%E4%B9%8B%E4%BB%8B',
  },
  {
    id: 15,
    title: '藪の中',
    author: '芥川龍之介',
    year: '1922年',
    genre: '短編小説',
    emoji: '🌿',
    passage: `わたしがあの死骸を見たのは、今日の午前のことでございます。`,
    desc: '平安時代を舞台に、ある男の死の真相を複数の証言から描く問題作。それぞれの語りが矛盾しあい、「真実」が最後まで明かされない構造は、現代のミステリやフィクション論に多大な影響を与えた。',
    link: 'https://www.aozora.gr.jp/cards/000879/files/179_15255.html',
    shopLink: 'https://www.amazon.co.jp/s?k=%E8%97%AA%E3%81%AE%E4%B8%AD+%E8%8A%A5%E5%B7%9D%E9%BE%8D%E4%B9%8B%E4%BB%8B',
  },
  {
    id: 16,
    title: '注文の多い料理店',
    author: '宮沢賢治',
    year: '1924年',
    genre: '童話',
    emoji: '🍽️',
    passage: `二人の若い紳士が、すっかりイギリスの兵隊のかたちをして、ぴかぴかする鉄砲をかついで、白熊のような犬を二匹つれて、山奥の野原を歩いていました。`,
    desc: '宮沢賢治の童話集の表題作。山中で迷った二人の紳士が「山猫軒」という料理店に辿り着くが、そこには次々と奇妙な注文が——。ユーモアと恐怖が混在する、賢治童話の真骨頂。',
    link: 'https://www.aozora.gr.jp/cards/000081/files/1927_18377.html',
    shopLink: 'https://www.amazon.co.jp/s?k=%E6%B3%A8%E6%96%87%E3%81%AE%E5%A4%9A%E3%81%84%E6%96%99%E7%90%86%E5%BA%97+%E5%AE%AE%E6%B2%A2%E8%B3%A2%E6%B2%BB',
  },
  {
    id: 17,
    title: '高瀬舟',
    author: '森鴎外',
    year: '1916年',
    genre: '短編小説',
    emoji: '🚣',
    passage: `高瀬舟は京都の高瀬川を上下する小舟である。徳川時代に京都の罪人が遠島を申し渡されると、本人の親類が牢屋敷へ呼び出されて、そこから罪人を高瀬舟に乗せて大阪へ廻したものである。`,
    desc: '森鴎外の代表的短編。弟を安楽死させた罪で島流しにされる男が、なぜか穏やかな表情を見せる理由とは——。「足るを知る」ことと安楽死という普遍的なテーマを静謐な文体で問う。',
    link: 'https://www.aozora.gr.jp/cards/000129/files/694_15786.html',
    shopLink: 'https://www.amazon.co.jp/s?k=%E9%AB%98%E7%80%AC%E8%88%9F+%E6%A3%AE%E9%B4%8E%E5%A4%96',
  },
  {
    id: 18,
    title: '舞姫',
    author: '森鴎外',
    year: '1890年',
    genre: '浪漫主義小説',
    emoji: '💃',
    passage: `今宵は夜毎に陥りぬる虚惘の感じやはあると、一人笑みてあたりを見廻せしに、`,
    desc: '明治を代表するドイツ留学小説。ベルリンで貧しい踊り子エリスと恋に落ちた青年が、立身出世と愛の間で苦悩する。文語体の美しい文章で綴られた、日本近代文学最初の「自我の覚醒」の物語。',
    link: 'https://www.aozora.gr.jp/cards/000129/files/686_15786.html',
    shopLink: 'https://www.amazon.co.jp/s?k=%E8%88%9E%E5%A7%AB+%E6%A3%AE%E9%B4%8E%E5%A4%96',
  },
  {
    id: 19,
    title: '堕落論',
    author: '坂口安吾',
    year: '1946年',
    genre: 'エッセイ・評論',
    emoji: '🔥',
    passage: `戦争に負けたから堕ちるのではないのだ。人間だから堕ちるのであり、生きているから堕ちるだけだ。`,
    desc: '終戦直後、廃墟の中で書かれた衝撃の評論。「堕落せよ」と叫ぶ安吾は、戦後の混乱を正面から肯定し、人間の本質的な「生」を問う。戦後精神の原点とも呼ばれる問題作。',
    link: 'https://www.aozora.gr.jp/cards/001095/files/42620_21407.html',
    shopLink: 'https://www.amazon.co.jp/s?k=%E5%A0%95%E8%90%BD%E8%AB%96+%E5%9D%82%E5%8F%A3%E5%AE%89%E5%90%BE',
  },
  {
    id: 20,
    title: '徒然草',
    author: '兼好法師',
    year: '14世紀初頭',
    genre: '随筆・古典',
    emoji: '📜',
    passage: `つれづれなるままに、日暮らし硯に向かひて、心にうつりゆくよしなし事を、そこはかとなく書き付くれば、あやしうこそものぐるほしけれ。`,
    desc: '鎌倉末期〜南北朝の随筆。「いとをかし」と共に日本の美意識の根幹をなす「あはれ」の感覚が随所に溢れる。無常観・人生論・自然への眼差しを通じて今も読者の心に語りかける古典の金字塔。',
    link: 'https://www.aozora.gr.jp/cards/001779/files/56642_57592.html',
    shopLink: 'https://www.amazon.co.jp/s?k=%E5%BE%92%E7%84%B6%E8%8D%89+%E5%85%BC%E5%A5%BD%E6%B3%95%E5%B8%AB',
  },
  {
    id: 21,
    title: '枕草子',
    author: '清少納言',
    year: '11世紀初頭',
    genre: '随筆・古典',
    emoji: '🌸',
    passage: `春はあけぼの。やうやう白くなりゆく山ぎは少し明かりて、紫だちたる雲の細くたなびきたる。`,
    desc: '平安中期、一条天皇の中宮定子に仕えた清少納言による随筆。四季の自然から宮廷の機知まで、鋭い観察眼と「をかし」の美意識で綴られた約300段は、日本最初のエッセイとも言われる。',
    link: 'https://www.aozora.gr.jp/cards/000183/files/973_28127.html',
    shopLink: 'https://www.amazon.co.jp/s?k=%E6%9E%95%E8%8D%89%E5%AD%90+%E6%B8%85%E5%B0%91%E7%B4%8D%E8%A8%80',
  },
  {
    id: 22,
    title: '武蔵野',
    author: '国木田独歩',
    year: '1901年',
    genre: '自然文学',
    emoji: '🌲',
    passage: `武蔵野の美はその曠野と林と、すなわちそれをもととした諸種の美の混合から生まれている。`,
    desc: '明治の自然文学の傑作。東京近郊に広がる武蔵野の四季の移ろいを詩的な散文で描きながら、自然と人間、孤独と祈りについて静かに問いかける。短編「忘れえぬ人々」も収録。',
    link: 'https://www.aozora.gr.jp/cards/000038/files/2330_10221.html',
    shopLink: 'https://www.amazon.co.jp/s?k=%E6%AD%A6%E8%94%B5%E9%87%8E+%E5%9B%BD%E6%9C%A8%E7%94%B0%E7%8B%AC%E6%AD%A9',
  },
  {
    id: 23,
    title: 'よだかの星',
    author: '宮沢賢治',
    year: '1921年（没後刊）',
    genre: '童話',
    emoji: '⭐',
    passage: `よだかは、実にみにくい鳥です。顔は、ところどころ、味噌をつけたようにまだらで、くちばしは、ひらたくて、耳まで裂けています。そして足は、まるでよぼよぼで、一間もあるいたら、もうたおれそうになります。`,
    desc: '醜いと疎まれ孤独なよだかが、最後に星になるまでを描いた賢治の童話。弱者への愛、存在の悲しみ、そして魂の解放——数ページの短い物語の中に、宇宙的な優しさが詰まっている。',
    link: 'https://www.aozora.gr.jp/cards/000081/files/1924_18371.html',
    shopLink: 'https://www.amazon.co.jp/s?k=%E3%82%88%E3%81%A0%E3%81%8B%E3%81%AE%E6%98%9F+%E5%AE%AE%E6%B2%A2%E8%B3%A2%E6%B2%BB',
  },
  {
    id: 24,
    title: '斜陽',
    author: '太宰治',
    year: '1947年',
    genre: '長編小説',
    emoji: '🌅',
    passage: `私は貴族です。\n\nお母さまも貴族です。けれども、私たちは、いま、没落しかけているのです。そうして、私も、お母さまも、それを、わかっています。`,
    desc: '戦後の没落貴族を描いた太宰の長編。「革命」を夢見る弟かず子と、時代に取り残されながらも気品を失わない母、退廃する弟直治。三者の運命を通じて、戦後日本の精神的崩壊を描く。',
    link: 'https://www.aozora.gr.jp/cards/000035/files/1565_8559.html',
    shopLink: 'https://www.amazon.co.jp/s?k=%E6%96%9C%E9%99%BD+%E5%A4%AA%E5%AE%B0%E6%B2%BB',
  },
  {
    id: 25,
    title: '高野聖',
    author: '泉鏡花',
    year: '1900年',
    genre: '幻想文学',
    emoji: '🌙',
    passage: `その声は、低く、しかしよく透る声だった。`,
    desc: '泉鏡花の出世作にして代表作。高野山へ向かう若い旅僧が山中で出会う美しい女と魔界——。官能と恐怖、聖と俗が交錯する幻想的な世界は、鏡花文学の神髄を示す。',
    link: 'https://www.aozora.gr.jp/cards/000050/files/339_19586.html',
    shopLink: 'https://www.amazon.co.jp/s?k=%E9%AB%98%E9%87%8E%E8%81%96+%E6%B3%89%E9%8F%A1%E8%8A%B1',
  },
  {
    id: 26,
    title: '或る女',
    author: '有島武郎',
    year: '1919年',
    genre: '長編小説',
    emoji: '🚢',
    passage: `葉子は甲板の欄干にもたれて、遠ざかってゆく神戸の港をぼんやり眺めていた。`,
    desc: '明治末期の新しい女・葉子を主人公に、自我と愛の激しい葛藤を描いた有島の代表作。女性の自立と破滅を正面から描いた作品として、近代日本文学の中でも異彩を放ち続ける。',
    link: 'https://www.aozora.gr.jp/cards/000025/files/1055_15176.html',
    shopLink: 'https://www.amazon.co.jp/s?k=%E6%88%96%E3%82%8B%E5%A5%B3+%E6%9C%89%E5%B3%B6%E6%AD%A6%E9%83%8E',
  },
  {
    id: 27,
    title: '破戒',
    author: '島崎藤村',
    year: '1906年',
    genre: '自然主義小説',
    emoji: '⛩️',
    passage: `瀬川丑松は、父の誡めを守って、今日まで人知れずに過ごして来た。しかし今となっては、もはや、その誡めを守りとほすことが出来なかった。`,
    desc: '部落差別という重いテーマに正面から向き合った日本自然主義の金字塔。教師の丑松が隠し続けてきた出自を打ち明ける「破戒」の場面は、近代文学屈指のクライマックスとして知られる。',
    link: 'https://www.aozora.gr.jp/cards/000158/files/1569_18779.html',
    shopLink: 'https://www.amazon.co.jp/s?k=%E7%A0%B4%E6%88%92+%E5%B3%B6%E5%B4%8E%E8%97%A4%E6%9D%91',
  },
  {
    id: 28,
    title: 'みだれ髪',
    author: '与謝野晶子',
    year: '1901年',
    genre: '短歌集',
    emoji: '🌺',
    passage: `やは肌のあつき血汐にふれも見でさびしからずや道を説く君`,
    desc: '明治の女性歌人・与謝野晶子が28歳で発表した処女歌集。情熱的で官能的な愛の歌399首は、当時の文壇を震撼させた。「女性の自由」を高らかに謳いあげた、近代短歌の革命的出発点。',
    link: 'https://www.aozora.gr.jp/cards/000885/files/3_15957.html',
    shopLink: 'https://www.amazon.co.jp/s?k=%E3%81%BF%E3%81%A0%E3%82%8C%E9%AB%AA+%E4%B8%8E%E8%AC%9D%E9%87%8E%E6%99%B6%E5%AD%90',
  },
  {
    id: 29,
    title: '鼻',
    author: '芥川龍之介',
    year: '1916年',
    genre: '短編小説',
    emoji: '👃',
    passage: `禅智内供の鼻と云えば、池の尾で知らない者はない。長さは五六寸あって上唇の上から顋の下まで下っている。`,
    desc: '芥川の初期代表作。今昔物語を下敷きに、長い鼻を持つ僧の悩みと、それが治った後の人間心理を鋭く描く。「他人の不幸を気の毒に思う半面、その不幸が解決されるとつまらなく思う」——傍観者の利己心を痛烈に諷刺する。',
    link: 'https://www.aozora.gr.jp/cards/000879/files/42_15228.html',
    shopLink: 'https://www.amazon.co.jp/s?k=%E9%BC%BB+%E8%8A%A5%E5%B7%9D%E9%BE%8D%E4%B9%8B%E4%BB%8B',
  },
  {
    id: 30,
    title: '地獄変',
    author: '芥川龍之介',
    year: '1918年',
    genre: '短編小説',
    emoji: '🎭',
    passage: `あの絵師は、この国に並ぶ者のないほど、優れた天才でございました。`,
    desc: '極限の芸術への狂気を描いた芥川の問題作。「芸術のためなら何でもやる」絵師・良秀が大殿様に命じられた地獄変の屏風絵を完成させるまでの凄絶な物語。芸術と人倫の究極の対立を描く。',
    link: 'https://www.aozora.gr.jp/cards/000879/files/95_15255.html',
    shopLink: 'https://www.amazon.co.jp/s?k=%E5%9C%B0%E7%8D%84%E5%A4%89+%E8%8A%A5%E5%B7%9D%E9%BE%8D%E4%B9%8B%E4%BB%8B',
  },
  {
    id: 31,
    title: 'セロ弾きのゴーシュ',
    author: '宮沢賢治',
    year: '1934年（没後刊）',
    genre: '童話',
    emoji: '🎻',
    passage: `ゴーシュは町の活動写真館でセロを弾く係りでした。けれどもあんまり上手でないという評判でした。`,
    desc: '下手なチェロ奏者ゴーシュのもとへ、夜な夜な動物たちが訪れる。最初は迷惑がるゴーシュだが、やがて——。賢治が生涯最後まで書き続けた童話。音楽と魂の成長を描いた温かな傑作。',
    link: 'https://www.aozora.gr.jp/cards/000081/files/470_15407.html',
    shopLink: 'https://www.amazon.co.jp/s?k=%E3%82%BB%E3%83%AD%E5%BC%BE%E3%81%8D%E3%81%AE%E3%82%B4%E3%83%BC%E3%82%B7%E3%83%A5+%E5%AE%AE%E6%B2%A2%E8%B3%A2%E6%B2%BB',
  },
  {
    id: 32,
    title: '風の又三郎',
    author: '宮沢賢治',
    year: '1934年（没後刊）',
    genre: '童話',
    emoji: '💨',
    passage: `どっどど どどうど どどうど どどう\n青いくるみも吹きとばせ\nすっぱいかりんも吹きとばせ\nどっどど どどうど どどうど どどう`,
    desc: '山奥の小学校に突然転校してきた赤髪の少年・三郎は、風の神の子なのか——。子どもたちの交流と別れを通じて、異質なものへの憧れと恐れを描く。賢治の土地への愛が息づく名作童話。',
    link: 'https://www.aozora.gr.jp/cards/000081/files/473_15411.html',
    shopLink: 'https://www.amazon.co.jp/s?k=%E9%A2%A8%E3%81%AE%E5%8F%88%E4%B8%89%E9%83%8E+%E5%AE%AE%E6%B2%A2%E8%B3%A2%E6%B2%BB',
  },
  {
    id: 33,
    title: '富嶽百景',
    author: '太宰治',
    year: '1939年',
    genre: '短編小説',
    emoji: '🗻',
    passage: `富士には、月見草がよく似合ふ。\n\nバスの中で私は、そつと、そんな言葉を口にした。`,
    desc: '太宰が御坂峠の茶屋に滞在し富士山と向き合いながら書いた自伝的短編。「富士には、月見草がよく似合ふ」の一文は日本文学に残る名句。人間的な弱さと誠実さを静かに描く。',
    link: 'https://www.aozora.gr.jp/cards/000035/files/2253_10929.html',
    shopLink: 'https://www.amazon.co.jp/s?k=%E5%AF%8C%E5%B6%BD%E7%99%BE%E6%99%AF+%E5%A4%AA%E5%AE%B0%E6%B2%BB',
  },
];
